apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-web
  template:
    metadata:
      labels:
        app: spring-boot-web
    spec:
      containers:
      - name: spring-boot-web
        image: nawfaladil/spring-boot-web-service:latest
        ports:
        - containerPort: 8080
